#
# Rewarding Achievements Configuration File
#
# For the source code visit my grave.
#

version: 1

# Add Quests to this file
# Each quest requires a unique identifier
# Follow the structure of the default quests
# name: "Name Title for Quest"
# trade: <item>, <amount>
# reward: <item>, <amount>

quests:
  1:
    name: "&2Black Earth"
    trade: dirt, 32
    reward: phantom_membrane, 1
  2:
    name: "&6Sweet Honey"
    trade: honey_bottle, 16
    reward: phantom_membrane, 3
  3:
    name: "&aSugary Cane"
    trade: sugar_cane, 64
    reward: phantom_membrane, 1
  4:
    name: "&8Black Gold"
    trade: coal, 32
    reward: phantom_membrane, 1

# When updating config - remove old config file from server.  So far needed for test server, have not tested on real server