#
# Rewarding Achievements Configuration File
#
# For the source code visit my grave.
#

version: 1
Command_Aliases: [ rewardingachievements, ra ]


# Add Quests to this file
# Each quest requires a unique identifier
# Follow the structure of the default quests
# name: "Name Title for Quest"
# trade: <item>, <amount>
# reward: <item>, <amount>

quests:
  1:
    name: "&6Sweet Honey"
    trade: honey_bottle, 16
    reward: phantom_membrane, 5
  2:
    name: "&5Venom of the Sea"
    trade: pufferfish, 10
    reward: phantom_membrane, 50
  3:
    name: "&2Black Earth"
    trade: dirt, 32
    reward: phantom_membrane, 1
  4:
    name: "&8Black Gold"
    trade: coal, 32
    reward: phantom_membrane, 1
  5:
    name: "&3Irish Potatoes"
    trade: potato, 64
    reward: phantom_membrane, 2
  6:
    name: "&aRabbit Food"
    trade: carrot, 64
    reward: phantom_membrane, 3
  7:
    name: "&9Beets"
    trade: beetroot, 32
    reward: phantom_membrane, 2
  8:
    name: "&5Piglin's Berries"
    trade: nether_wart, 64
    reward: phantom_membrane, 10
  9:
    name: "&aVillagers Coin"
    trade: emerald, 20
    reward: phantom_membrane, 25
  10:
    name: "&6Beeautiful Honey"
    trade: honey_bottle, 128
    reward: phantom_membrane, 50
  11:
    name: "&aSugary Cane"
    trade: sugar_cane, 64
    reward: phantom_membrane, 1
  12:
    name: "&eBanquettes"
    trade: bread, 32
    reward: phantom_membrane, 5
  13:
    name: "&bFresh Salmon"
    trade: cooked_salmon, 32
    reward: phantom_membrane, 6
  14:
    name: "&dStandard Issue Iron"
    trade: iron_ingot, 64
    reward: phantom_membrane, 10
  15:
    name: "&5Dragon Fruit"
    trade: chorus_fruit, 32
    reward: phantom_membrane, 25
  16:
    name: "&3Sea Cows Favorite"
    trade: seagrass, 32
    reward: phantom_membrane, 5
  17:
    name: "&cFuji Apples"
    trade: apple, 16
    reward: phantom_membrane, 10
  18:
    name: "&5Magical Orbs"
    trade: ender_pearl, 16
    reward: phantom_membrane, 15
  19:
    name: "&eNatural Honey Makers"
    trade: bee_nest, 10
    reward: phantom_membrane, 100
  20:
    name: "&dGrandmas Cookies"
    trade: cookie, 64
    reward: phantom_membrane, 3
  21:
    name: "&5Snow Berries"
    trade: sweet_berries, 64
    reward: phantom_membrane, 3
  22:
    name: "&4Resurrecting Stones"
    trade: totem_of_undying, 3
    reward: phantom_membrane, 100
  23:
    name: "&aBaby Turtle Shells"
    trade: scute, 10
    reward: phantom_membrane, 20
  24:
    name: "&cCooked Hoppers"
    trade: cooked_rabbit, 32
    reward: phantom_membrane, 5
  25:
    name: "&9Me Good Luck Charms"
    trade: rabbit_foot, 10
    reward: phantom_membrane, 25
  26:
    name: "&cFiery Furnace"
    trade: blaze_rod, 16
    reward: phantom_membrane, 32
  27:
    name: "&3Buried Treasure"
    trade: heart_of_the_sea, 10
    reward: phantom_membrane, 50

# When updating config - remove old config file from server.  So far needed for test server, have not tested on real server